### ISSUE TITLE
Gem doesn't provide a "bundled" turbo_power.js

### ISSUE THREAD

**Issue by minimul** [marcoroth/turbo_power-rails#10]
Hey @marcoroth

I just tried to do a:
``` 
pin "turbo_power", to: "turbo_power.js"
```
as in the README (instructions I put in with my PR 😀 btw) and the browser console throws an error that `turbo_power.js` cannot be found.

I looked in the Rails asset paths `Rails.application.assets.paths.map { |path| puts system("ls #{path}/") }; nil` and yeah, there is no `turbo_power.js` nor any paths provided from this gem.

I'm using the latest `gem 'turbo_power'`, which at this time is `0.1.6`.

**Comment by marcoroth** [comment]
Hey @minimul, thanks for spotting this, you are right!

I put up #4 to address this, but I didn't realize that the instructions in the README were already relying on this and thus not working as expected yet.

As a workaround I would suggest to use the CDN:

```ruby
pin "turbo_power", to: "https://cdn.jsdelivr.net/npm/turbo_power@0.1.6/dist/index.js"
# or
pin "turbo_power", to: "https://ga.jspm.io/npm:turbo_power@0.1.6/dist/index.js"
```

I'm going to update the README for now until #4 is resolved.

**Comment by minimul** [comment]
Closing #4 will take care of this issue but README needed to be changed and was in a recent commit.
