### ISSUE TITLE
turbo-rails 1.4

### ISSUE THREAD

**Issue by drnic** [marcoroth/turbo_power-rails#29]
Bump gemspec to allow https://github.com/hotwired/turbo-rails/releases/tag/v1.4.0

**Comment by marcoroth** [comment]
Hey @drnic, doesn't `0.3.1` allow this already?

https://github.com/marcoroth/turbo_power-rails/releases/tag/v0.3.1

**Comment by drnic** [comment]
Ah, sorry I had `gem "turbo_power", "~> 0.2.0"` holding me back.
