### ISSUE TITLE
Detail on dispatch event seems to not get sent

### ISSUE THREAD

**Issue by dqnamo** [marcoroth/turbo_power-rails#42]
My code in the model: `broadcast_dispatch_event_to user, target: 'calendar-container', name: 'move-event', detail: { task_id: id, start: calendar_start, end: calendar_end }`
![CleanShot 2024-06-06 at 12 21 03@2x](https://github.com/marcoroth/turbo_power-rails/assets/25507937/78710af3-bf8a-4c9b-bc2d-82ab543540a0)

**Comment by marcoroth** [comment]
Thanks for reporting, @dqnamo. I put up #43 to address this!
